spring:
  application:
    name: notification-microservice

  mail:
    host: ${EMAIL_HOST:some_host}
    username: ${EMAIL_USERNAME:some_user'}
    password: ${EMAIL_PASSWORD:some_password}
    port: ${EMAIL_PORT:800}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:
              true

  elasticsearch:
    connection-timeout: 1m
    socket-timeout: 1m
    socket-keep-alive: true
  rabbitmq:
    connection-timeout: 30s

scheduler:
  cron-expr: '0 */5 * * * *'

elasticsearch:
  address: ${ELASTICSEARCH_ADDRESS}

