spring:
  application:
    name: notification-microservice
  elasticsearch:
    connection-timeout: 30s
    socket-keep-alive: true
    socket-timeout: 2m
  rabbitmq:
    username: user
    password: password
    host: localhost
    port: 5672
    connection-timeout: 15s

elasticsearch:
  address: 'localhost:9200'