spring:
  application:
    name: notification-microservice

  mail:
    host: ${EMAIL_HOST}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    port: ${EMAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable:
              true

  elasticsearch:
    connection-timeout: 30s
  rabbitmq:
    connection-timeout: 15000

elasticsearch:
  address: 'elasticsearch:9200'

